n1 = int(input('Um valor: '))
n2 = int(input('Outro valor: '))
print('A soma é {}'.format(n1 + n2), end=' ')
print('A subtração é {}'.format(n1 - n2))
print('A multiplicação é {}'.format(n1 * n2))
print('A divisão é {:.3f}'.format(n1 / n2))
print('A divisão inteira é {}'.format(n1 // n2))
print('O resto da divisão é {}'.format(n1 % n2))
print('A exponenciação é {}'.format(n1 ** n2))
